name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract version from pubspec.yaml
      id: extract_version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | head -n 1 | awk '{print $2}')
        echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/dalifeinu:${{ env.IMAGE_TAG }}

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/dalifeinu:${{ env.IMAGE_TAG }}